# Use the official Node.js image as base
FROM node:latest

# Set working directory
WORKDIR /usr/src/frontend

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Build the frontend application
RUN npm run build

# Expose port 3000
EXPOSE 3000

# Command to run the frontend application
CMD ["npm", "start"]
