version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb+srv://ayush:ayush@cluster0.i09ljc9.mongodb.net/velvet_homes?retryWrites=true&w=majority
    restart: always
