# Use the official Node.js image as base
FROM node:latest

# Set working directory
WORKDIR /usr/src/backend

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Expose port 5000
EXPOSE 5000

# Command to run the backend application
CMD ["npm", "start"]
