name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install 
      env:
        CI: true
        
  build-and-deploy-frontend:
    name: Build and Deploy Frontend to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install --prefix frontend

      - name: Build frontend
        run: npm run build --prefix frontend

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-scope: ${{ secrets.VERCEL_SCOPE }}

  build-and-deploy-backend:
    name: Build and Deploy Backend to Render
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install --prefix backend

      - name: Deploy to Render
        uses: render-com/action@1.4
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          render-org-slug: ${{ secrets.RENDER_ORG_SLUG }}
          render-service-id: ${{ secrets.RENDER_SERVICE_ID }}
